In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [4]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [5]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median))

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount_usd'})

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [9]:
# create age group column

bins = [0, 18, 35, 60, 100]
labels = ['Underage', 'Young Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [10]:
df[['age', 'age_group']].head(15)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
5    46  Middle-aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle-aged
10   53  Middle-aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior

In [11]:
purchase_frequency = df['frequency_of_purchases'].value_counts()
print(purchase_frequency)

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [12]:
frequency_mapping = {
    'Every 3 Months': 90,
    'Annually': 365,
    'Quarterly': 90,
    'Monthly': 30,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Weekly': 7
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(15)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly

In [14]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [15]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [16]:
df.drop('promo_code_used', axis=1, inplace=True)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

# Connect to MySQL

In [18]:
pip install pymysql sqlalchemy cryptography

Requirement already satisfied: pymysql in C:\Users\darin\anaconda3\Lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\darin\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: cryptography in C:\Users\darin\anaconda3\Lib\site-packages (49.0.0)
Requirement already satisfied: greenlet>=1 in C:\Users\darin\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\darin\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\darin\anaconda3\Lib\site-packages (from cryptography) (2.1.0)
Requirement already satisfied: pycparser in C:\Users\darin\anaconda3\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sqlalchemy import create_engine

username = "root"              
password =  
host = "localhost"             
port = "3306"                  
database = "customer_behaviour" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

In [20]:
table_name = "customer"        
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.